### ISSUE TITLE
你好，这个获取的网站怎么是https://www.3ubdxu00l1lkcjoz5n.com/

### ISSUE THREAD

**Issue by EdisonChenZX** [raawaa/jav-scrapy#41]
y> jav -b http://www.javbus.in/genre/28
========== 获取资源站点：https://www.3ubdxu00l1lkcjoz5n.com/ ==========
并行连接数： 2        连接超时设置： 30 秒
磁链保存位置:  C:\Users\taw\magnets
代理服务器:  无
第1页页面获取失败：connect ETIMEDOUT 67.228.126.62:80
...进行第2次尝试...
第1页页面获取失败：connect ETIMEDOUT 67.228.126.62:80
...进行第3次尝试...
第1页页面获取失败：connect ETIMEDOUT 67.228.126.62:80
...进行第4次尝试...

**Comment by Dandelion1998** [comment]
啥？为啥问我 dandelion19980309 邮箱dandelion19980309@gmail.com 签名由 网易邮箱大师 定制 在2019年01月25日 16:57，EdisonChenZX 写道： y> jav -b http://www.javbus.in/genre/28 ========== 获取资源站点：https://www.3ubdxu00l1lkcjoz5n.com/ ========== 并行连接数： 2 连接超时设置： 30 秒 磁链保存位置: C:\Users\taw\magnets 代理服务器: 无 第1页页面获取失败：connect ETIMEDOUT 67.228.126.62:80 ...进行第2次尝试... 第1页页面获取失败：connect ETIMEDOUT 67.228.126.62:80 ...进行第3次尝试... 第1页页面获取失败：connect ETIMEDOUT 67.228.126.62:80 ...进行第4次尝试... — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by raawaa** [comment]
本尊域名国内被墙了，所以经常会换一下域名。
